# Generated by Django 3.0.5 on 2020-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='date',
            field=models.DateField(),
        ),
    ]
